const $ = s => document.querySelector(s);
const reduced = window.matchMedia('(prefers-reduced-motion: reduce)');
function updateClock(){ $('#clock').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}).format(new Date())+' IST'; }
updateClock(); setInterval(updateClock,60000); $('#year').textContent=new Date().getFullYear();
const projects={
james:{category:'Tap Invest / BondScanner',title:'James AI',summary:'Helping investors ask better questions, with answers connected to real bond data.',sections:[['The problem','Researching bonds means moving between financial data, holdings, and product information. A conversational interface is useful only when it stays connected to that context.'],['My contribution','Built backend integration for the assistant, including the Spring Boot controller, service, client and response contracts. The work covered streaming responses, structured render payloads, usage limits and cancellation-aware credit handling.'],['What mattered','The experience had to behave like a product: readable responses, predictable streaming, useful error states, and clear boundaries around what an AI answer can say.'],['Tools','Java · Spring Boot · Claude · Retrieval-augmented generation · Server-sent events']],link:['Visit BondScanner','https://bondscanner.com']},
sdui:{category:'Tap Invest / Mobile platforms',title:'Deal Details & server-driven UI',summary:'Connecting a shared UI contract, backend services and native mobile screens.',sections:[['The problem','A product changes more quickly than an app-store release cycle. Rebuilding each screen independently also makes consistent experiences harder to maintain.'],['My contribution','Worked across the Java UI contract library, backend-for-frontend services and Flutter apps. Deal Details V3 introduced flexible composition primitives, financial-data mapping and a versioned rollout. Other work spans onboarding, holdings and portfolio reports.'],['The idea','Keep presentation structured and reusable. The server describes the content and composition; the client renders it with familiar native components.'],['Tools','Java · Spring Boot · Go · Flutter · Versioned UI contracts']],link:['Explore Tap Invest','https://tapinvest.in']},
playrove:{category:'Independent project / Product, engineering & design',title:'PlayRove',summary:'Small games for a little daily satisfaction.',sections:[['The idea','Build a welcoming place to play browser puzzles, from word games and Queens to familiar logic challenges. Fast entry, clear rules and a reason to come back.'],['The engineering','PlayRove combines static browser games with daily puzzles, local statistics and optional ranked play. Its semantic word game uses an offline data pipeline to prepare compact rank data for browser-side guesses.'],['The details','I worked on the game experience, responsive layouts, touch controls, tutorials, data generation and deployment. The project is an ongoing playground for making software feel good to use.'],['Tools','JavaScript · Web Workers · Python · Netlify · Playwright']],link:['Play a game','https://playrove.netlify.app']},
sentinel:{category:'Tap Invest / Internal knowledge tooling',title:'Sentinel',summary:'An operations assistant that points back to its sources.',sections:[['The problem','Operational knowledge lives in runbooks. Finding the right passage quickly matters, and an answer without a supporting source can create more work than it saves.'],['My contribution','Built a knowledge assistant around document ingestion, retrieval and cited answers. The work included handling document updates, improving retrieval behavior and making unanswered questions useful feedback.'],['The design choice','Ground answers in uploaded knowledge and make uncertainty visible. If the available context cannot support an answer, the assistant should say so.'],['Tools','Python · FastAPI · PostgreSQL · Redis · Retrieval-augmented generation']]},
release:{category:'Tap Invest / Developer experience',title:'Less ceremony. More shipping.',summary:'A release workflow designed around the people who use it.',sections:[['My contribution','Built a service that accepts build requests through Google Chat and coordinates app builds through an AWS-backed queue. The workflow includes parallel jobs, app distribution and completion notices.'],['Why it matters','A release should not depend on one person having the right laptop and toolchain. A shared build workflow makes the path from a request to a distributable app easier to follow.'],['Tools','AWS SQS · SNS · Lambda · Google Chat · App distribution']]},
mcp:{category:'AI tooling / Platform integration',title:'Useful tools for useful agents.',summary:'Giving AI agents a structured way to work with real software.',sections:[['My contribution','Built MCP integrations that expose platform capabilities as typed, discoverable tools with structured returns. The goal is to make the data boundary explicit and keep agent interactions grounded in actual APIs.'],['Outside work','I also experiment with agent workflows and review tooling. These experiments are a way to understand where automation helps, where evidence is missing, and where a human decision still matters.'],['Tools','Model Context Protocol · TypeScript · Python · API integration']]},
ipo:{category:'Tap Invest / Investment products',title:'The whole investment journey.',summary:'Making the path through a financial product feel connected.',sections:[['My contribution','Worked on Bonds IPO services and mobile contracts, including exploration, deal details, cashflows, mandate and summary flows. Related work includes portfolio reports, bank addition and payment integrations.'],['Across the stack','These features need more than a screen: the API shape, shared models, user actions and state transitions all have to agree. That coordination is the part I especially enjoy.'],['Tools','Spring Boot · Java contracts · Flutter · REST APIs']]}}
const dialog=$('#project-dialog');
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const p=projects[button.dataset.project];$('#dialog-category').textContent=p.category;$('#dialog-title').textContent=p.title;$('#dialog-summary').textContent=p.summary;$('#dialog-content').replaceChildren(...p.sections.map(([title,text])=>{const section=document.createElement('section');const h=document.createElement('h3');h.textContent=title;const body=document.createElement('p');body.textContent=text;section.append(h,body);return section}));$('#dialog-links').replaceChildren();if(p.link){const a=document.createElement('a');a.className='button dark';a.href=p.link[1];a.target='_blank';a.rel='noopener';a.textContent=p.link[0]+' ↗';$('#dialog-links').append(a)}dialog.showModal();document.body.style.overflow='hidden';}));
$('#dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});
$('#copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('jayantnagori001@gmail.com');$('#copy-status').textContent='Email copied. Say hello!';}catch{$('#copy-status').textContent='Copy this address: jayantnagori001@gmail.com';}});
// Every starting board is generated by legal moves from the solved state.
let board=Array(9).fill(true),moves=0,solved=false,puzzleNumber=0;
const cells=[];const patterns=[[0,4,8],[1,3,5,7],[0,2,4,6],[2,3,7],[0,1,6,8]];
function toggle(i){const r=Math.floor(i/3),c=i%3;[[r,c],[r-1,c],[r+1,c],[r,c-1],[r,c+1]].forEach(([y,x])=>{if(y>=0&&y<3&&x>=0&&x<3)board[y*3+x]=!board[y*3+x]})}
function renderBoard(){cells.forEach((b,i)=>{b.setAttribute('aria-pressed',String(board[i]));b.setAttribute('aria-label',`Row ${Math.floor(i/3)+1}, column ${i%3+1}, ${board[i]?'on':'off'}`);b.textContent=board[i]?'✳':'·'});$('#move-count').textContent=moves+' '+(moves===1?'move':'moves')}
for(let i=0;i<9;i++){const b=document.createElement('button');b.type='button';b.addEventListener('click',()=>{if(solved)return;toggle(i);moves++;renderBoard();solved=board.every(Boolean);$('#puzzle-status').textContent=solved?`All lit up. Nicely done in ${moves} moves!`:'Keep going. Every move changes the picture.';});cells.push(b);$('#puzzle').append(b)}
function newGame(){board=Array(9).fill(true);patterns[puzzleNumber++%patterns.length].forEach(toggle);moves=0;solved=false;renderBoard();$('#puzzle-status').textContent='Your move.'}newGame();$('#reset-game').addEventListener('click',newGame);
// The 3D scene is progressive enhancement; the content never waits for WebGL.
import('./scene.js').catch(()=>{$('#explode').hidden=true;$('#motion').hidden=true;});

import('./scroll.js');
