import * as THREE from './assets/three.module.min.js';
const canvas=document.querySelector('#stack-canvas'),host=document.querySelector('#sculpture');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'low-power'});}catch(e){document.querySelector('#explode').hidden=true;document.querySelector('#motion').hidden=true;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0xf4f3ef,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.65;
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(32,1,.1,100);camera.position.set(7,6.5,10);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xffffff,0xb2b59e,3));const key=new THREE.DirectionalLight(0xfff7e9,5);key.position.set(-4,8,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;key.shadow.normalBias=.03;scene.add(key);const rim=new THREE.DirectionalLight(0xe1e8ff,2);rim.position.set(5,3,-5);scene.add(rim);
const assembly=new THREE.Group();scene.add(assembly);assembly.scale.setScalar(1.13);assembly.rotation.y=-.3;assembly.rotation.z=-.07;
function roundedShape(w,d,r){const s=new THREE.Shape(),x=-w/2,y=-d/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+d-r);s.quadraticCurveTo(x+w,y+d,x+w-r,y+d);s.lineTo(x+r,y+d);s.quadraticCurveTo(x,y+d,x,y+d-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s;}
function slab(w,d,h,color){const g=new THREE.ExtrudeGeometry(roundedShape(w,d,.23),{depth:h,bevelEnabled:true,bevelSize:.075,bevelThickness:.075,bevelSegments:4,steps:1,curveSegments:12});g.rotateX(-Math.PI/2);g.translate(0,-h/2,0);const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.32,metalness:.13}));m.castShadow=true;m.receiveShadow=true;return m;}
function textLabel(text,w,color,bg){const c=document.createElement('canvas');c.width=1024;c.height=160;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,1024,160);x.fillStyle=color;x.font='500 74px Arial';x.textBaseline='middle';x.fillText(text,60,88);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,w*160/1024),new THREE.MeshBasicMaterial({map:t}));return m;}
const layers=[];const colors=[0xb9c7a5,0x333b34,0xeb542c];const names=['infrastructure','intelligence','interface'];
for(let i=0;i<3;i++){const g=new THREE.Group();g.add(slab(3.75,2.8,.55,colors[i]));const label=textLabel(names[i],2.7,i===1?'#e6eadb':'#263027',['#b9c7a5','#333b34','#eb542c'][i]);label.position.set(-.15,.02,1.486);g.add(label);for(let x=-1.5;x<=1.5;x+=3){const screw=new THREE.Mesh(new THREE.CylinderGeometry(.046,.046,.027,12),new THREE.MeshStandardMaterial({color:0xd9dccc,metalness:.9,roughness:.2}));screw.position.set(x,.365,1.02);g.add(screw)}g.position.y=(i-1)*.81;g.rotation.y=(i-1)*.10;assembly.add(g);layers.push(g)}
// A removable ceramic interface tile sits above the physical stack.
const tile=slab(2.7,1.85,.06,0xf2efdf);tile.position.set(0,.35,0);layers[2].add(tile);
const tileCanvas=document.createElement('canvas');tileCanvas.width=768;tileCanvas.height=512;const ctx=tileCanvas.getContext('2d');ctx.fillStyle='#f2efdf';ctx.fillRect(0,0,768,512);ctx.fillStyle='#303b34';ctx.font='bold 74px Arial';ctx.fillText('hello, world.',58,112);ctx.fillStyle='#b7c5a3';ctx.beginPath();ctx.roundRect(58,155,652,220,22);ctx.fill();ctx.fillStyle='#eb542c';ctx.beginPath();ctx.arc(390,265,66,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f2efdf';ctx.font='80px Arial';ctx.textAlign='center';ctx.fillText('✳',390,294);ctx.fillStyle='#7d8673';ctx.fillRect(58,415,290,10);ctx.fillRect(58,442,190,10);ctx.fillStyle='#303b34';ctx.beginPath();ctx.roundRect(530,410,177,45,22);ctx.fill();const texture=new THREE.CanvasTexture(tileCanvas);texture.colorSpace=THREE.SRGBColorSpace;const topScreen=new THREE.Mesh(new THREE.PlaneGeometry(2.48,1.64),new THREE.MeshBasicMaterial({map:texture}));topScreen.rotation.x=-Math.PI/2;topScreen.position.set(0,.463,0);layers[2].add(topScreen);
// Fine connector pins make the exploded view read as an actual assembly.
for(let j=0;j<2;j++)for(let x of [-1.3,1.3])for(let z of [-.8,.8]){const pin=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.4,10),new THREE.MeshStandardMaterial({color:0xc4ba95,metalness:.8,roughness:.25}));pin.position.set(x,.48,z);layers[j].add(pin)}
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.1;floor.receiveShadow=true;scene.add(floor);
let expanded=false,paused=reduced.matches,visible=true,targetX=0,targetY=0,last=0,elapsed=0,raf=0;
const motion=document.querySelector('#motion'),explode=document.querySelector('#explode');
function syncMotion(){motion.textContent=paused?'▷':'Ⅱ';motion.setAttribute('aria-pressed',String(paused));motion.setAttribute('aria-label',paused?'Resume sculpture motion':'Pause sculpture motion')}
syncMotion();explode.addEventListener('click',()=>{expanded=!expanded;explode.setAttribute('aria-pressed',String(expanded));explode.innerHTML=expanded?'Put it together <span>−</span>':'Take it apart <span>＋</span>';if(reduced.matches){layers.forEach((g,i)=>{g.position.y=(i-1)*(expanded?1.55:.81)});renderOnce()}else start()});motion.addEventListener('click',()=>{paused=!paused;syncMotion();start()});reduced.addEventListener('change',()=>{paused=reduced.matches;syncMotion();start()});
host.addEventListener('pointermove',e=>{if(reduced.matches||paused)return;const r=host.getBoundingClientRect();targetY=((e.clientX-r.left)/r.width-.5)*.5;targetX=((e.clientY-r.top)/r.height-.5)*.16;start()});host.addEventListener('pointerleave',()=>{targetX=targetY=0;start()});
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.set(7,6.5,10).multiplyScalar(w<400?1.1:1);camera.updateProjectionMatrix();camera.lookAt(0,0,0);renderOnce()}function renderOnce(){renderer.render(scene,camera)}
function tick(t){raf=0;if(!visible||document.hidden)return;const dt=Math.min((t-last)/1000,.04);last=t;if(!paused)elapsed+=dt;let moving=false;layers.forEach((g,i)=>{const desired=(i-1)*(expanded?1.55:.81);g.position.y+=(desired-g.position.y)*.09;if(Math.abs(desired-g.position.y)>.001)moving=true;});assembly.rotation.y+=(-.3+targetY+(paused?0:Math.sin(elapsed*.38)*.08)-assembly.rotation.y)*.055;assembly.rotation.x+=(targetX-assembly.rotation.x)*.055;assembly.position.y=paused?0:Math.sin(elapsed*.65)*.05;renderOnce();if(!paused||moving)raf=requestAnimationFrame(tick)}function start(){if(!raf&&visible&&!document.hidden){last=performance.now();raf=requestAnimationFrame(tick)}}new ResizeObserver(resize).observe(host);new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible)start()},{rootMargin:'100px'}).observe(host);document.addEventListener('visibilitychange',()=>{if(!document.hidden)start()});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(raf);host.classList.remove('webgl-ready');explode.hidden=true;motion.hidden=true});resize();host.classList.add('webgl-ready');start();
